package com.example.demo.entity;
import jakarta.persistence.*;
import lombok.Data;
@Data
@Entity
@Table(name = "job_post_table")

public class Job_post_table {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="id")
    private Integer id;
    @Column(name = "post_time", length = 255)
    private String postTime;

    @Column(name = "job_number")
    private Integer jobNumber;

    // Constructors are automatically generated by @Data
    // No need to explicitly define getters and setters

    // You can optionally add other constructors if needed



}
