package com.example.demo.entity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
@Data
@Entity
@Table(name = "job_post_table")

public class Job_post_table {
    @Id
    @Column(name = "post_time", length = 255)
    private String postTime;

    @Column(name = "job_number")
    private Integer jobNumber;

    // Constructors are automatically generated by @Data
    // No need to explicitly define getters and setters

    // You can optionally add other constructors if needed



}
