package com.example.demo.entity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
@Data
@Entity
@Table(name = "job_salary_table")
public class Job_salary_table {

    @Id
    @Column(name = "time")
    private Integer time;

    @Column(name = "job", length = 255)
    private String job;

    @Column(name = "salary")
    private Double salary;

    // Constructors are automatically generated by @Data
    // No need to explicitly define getters and setters

    // You can optionally add other constructors if needed

}
