package com.example.demo.entity;
import jakarta.persistence.*;
import lombok.Data;
@Data
@Entity
@Table(name = "job_salary_table")
public class Job_salary_table {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name="id")
    private Integer id;
    @Column(name = "dt")
    private Integer time;

    @Column(name = "job", length = 255)
    private String job;

    @Column(name = "salary")
    private Double salary;

    // Constructors are automatically generated by @Data
    // No need to explicitly define getters and setters

    // You can optionally add other constructors if needed

}
